<a href="https://colab.research.google.com/github/KalidaCh/bsc_dpdm22/blob/main/add%20Precision%20%26%20Recall.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets

iris_data = datasets.load_iris()

In [2]:
X = iris_data['data']

y = iris_data['target']

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, KFold

In [4]:
model = DecisionTreeClassifier()

# Define the k-fold cross validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Train and evaluate the model using 10-fold cross validation
scores = cross_val_score(model, X, y, cv=kf)

# Print the average accuracy and standard deviation across all folds
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.95 (+/- 0.12)

In [5]:
model = DecisionTreeClassifier(max_depth=2)

# Define the k-fold cross validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Train and evaluate the model using 10-fold cross validation
scores = cross_val_score(model, X, y, cv=kf)

# Print the average accuracy and standard deviation across all folds
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.95 (+/- 0.12)

In [6]:
from sklearn.model_selection import LeaveOneOut

In [7]:
model = DecisionTreeClassifier(max_depth=2)

# Define the k-fold cross validation
LOO = LeaveOneOut()

# Train and evaluate the model using 10-fold cross validation
scores = cross_val_score(model, X, y, cv=LOO)

# Print the average accuracy and standard deviation across all folds
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.95 (+/- 0.42)

In [8]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

transform numpy array to dataframe

In [9]:
import pandas as pd

In [10]:
columns = iris_data['feature_names']
X_df = pd.DataFrame(X, columns=columns)

In [11]:
X_df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [12]:
X_df['label']=y

In [13]:
X_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [14]:
shuffled_df = X_df.sample(frac=1,random_state=6)
shuffled_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
4,5.0,3.6,1.4,0.2,0
116,6.5,3.0,5.5,1.8,2
2,4.7,3.2,1.3,0.2,0
23,5.1,3.3,1.7,0.5,0
123,6.3,2.7,4.9,1.8,2
...,...,...,...,...,...
148,6.2,3.4,5.4,2.3,2
79,5.7,2.6,3.5,1.0,1
109,7.2,3.6,6.1,2.5,2
106,4.9,2.5,4.5,1.7,2
138,6.0,3.0,4.8,1.8,2

In [15]:
shuffled_df['fold']=15*[1,2,3,4,5,6,7,8,9,10]

In [16]:
shuffled_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label,fold
4,5.0,3.6,1.4,0.2,0,1
116,6.5,3.0,5.5,1.8,2,2
2,4.7,3.2,1.3,0.2,0,3
23,5.1,3.3,1.7,0.5,0,4
123,6.3,2.7,4.9,1.8,2,5
...,...,...,...,...,...,...
148,6.2,3.4,5.4,2.3,2,6
79,5.7,2.6,3.5,1.0,1,7
109,7.2,3.6,6.1,2.5,2,8
106,4.9,2.5,4.5,1.7,2,9
138,6.0,3.0,4.8,1.8,2,10

In [17]:
shuffled_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label,fold
4,5.0,3.6,1.4,0.2,0,1
116,6.5,3.0,5.5,1.8,2,2
2,4.7,3.2,1.3,0.2,0,3
23,5.1,3.3,1.7,0.5,0,4
123,6.3,2.7,4.9,1.8,2,5
...,...,...,...,...,...,...
148,6.2,3.4,5.4,2.3,2,6
79,5.7,2.6,3.5,1.0,1,7
109,7.2,3.6,6.1,2.5,2,8
106,4.9,2.5,4.5,1.7,2,9
138,6.0,3.0,4.8,1.8,2,10

อยากแบ่งว่าอันไหน test อันไหน train

# HW6 วนลูปทำ 10-fold cross validation

ขั้นตอนในการทำ10-fold cross validation:

แบ่งชุดข้อมูลออกเป็น 10 ส่วน โดย

- ใช้ 9 folds training data

- ใช้ 1 foldที่เหลือเป็น validation data
- train model ด้วยการ training data
- evaluate model จาก validation data

ทำซ้ำขั้นตอนที่ 2 สำหรับแต่ละ10 folds โดยใช้folds ที่แตกต่างกัน validation data 

คำนวณ accuracy,score ต่าง ๆ จากทั้ง 10 folds เพื่อให้ได้ประสิทธิภาพโดยรวมของโมเดล

k-fold cv คือการแบ่งข้อมูลเป็น k ส่วนเท่าๆกันเพื่อสร้างและทดสอบโมเดล (train + validate) 
คำนวณค่าเฉลี่ย accuracy หรือ error (i.e. model performance) ก่อนที่จะนำโมเดลไปใช้ทำนายข้อมูล เช่น การแบ่งข้อมูลเป็น 10 folds เท่าๆกัน โดยการแบ่งข้อมูลต้องเป็นไปอย่าง random

ทำไมต้อง random? เพราะ randomness จะช่วยให้ข้อมูลในแต่ละ fold มีการกระจายตัวใกล้เคียงกัน ช่วยลด bias เวลาที่เราสร้างและทดสอบโมเดล

##evaluate with loob of  10-fold cross validation

In [31]:
from sklearn.metrics import accuracy_score
import numpy as np
#แบ่ง test แยกด้วย fold
test_fold = 1
test_data = shuffled_df[shuffled_df['fold']==test_fold]
training_data = shuffled_df[shuffled_df['fold']!=test_fold] #ไม่เท่ากับ 1
# test_data.head()
X_test = test_data.iloc[:,:-2] #ดัด data ด้านคอลัมน์ #แบ่งฟีเจอร์ ไม่เอา 2 คอลัมน์สุดท้าย
y_test = test_data.iloc[:,-2] #จะเอาแค่คอลัมน์ที่ 2 นับจากท้าย
X_train = training_data .iloc[:,:-2]
y_train = training_data .iloc[:,-2] 
model = DecisionTreeClassifier(max_depth=2)
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
acc = accuracy_score(y_test,y_predict)
print(f'accuracy of fold{test_fold}= {acc}')

accuracy of fold1= 0.8666666666666667

In [32]:
acc_fold=[]
for test_fold in range(1,11):
    test_data = shuffled_df[shuffled_df['fold']==test_fold]
    training_data = shuffled_df[shuffled_df['fold']!=test_fold] #ไม่เท่ากับ 1
# test_data.head() #ตัดว่าอันไหนเป็นtest อันไหนเปน trian
    X_test = test_data.iloc[:,:-2] #ดัด data ด้านคอลัมน์ #แบ่งฟีเจอร์
    y_test = test_data.iloc[:,-2] #จะเอาแค่คอลัมน์ที่ -2อย่างเดียว
    X_train = training_data .iloc[:,:-2]
    y_train = training_data .iloc[:,-2] 
    model = DecisionTreeClassifier(max_depth=2)
    model.fit(X_train, y_train)
    y_predict = model.predict(X_test)
    acc = accuracy_score(y_test,y_predict)
    print(f'accuracy of fold{test_fold}= {acc}')
    acc_fold.append(acc)
print(f'accuracy of fold{np.mean(acc)}')

accuracy of fold1= 0.8666666666666667
accuracy of fold2= 1.0
accuracy of fold3= 0.9333333333333333
accuracy of fold4= 1.0
accuracy of fold5= 0.9333333333333333
accuracy of fold6= 0.9333333333333333
accuracy of fold7= 0.9333333333333333
accuracy of fold8= 1.0
accuracy of fold9= 0.8666666666666667
accuracy of fold10= 0.9333333333333333
accuracy of fold0.9333333333333333

#add Precision & Recall

In [36]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import precision_score, recall_score

# Load the iris dataset
iris = load_iris()

# Define the decision tree model
model = DecisionTreeClassifier()

# Define the k-fold cross validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Train and evaluate the model using 10-fold cross validation
precision_scores = []
recall_scores = []
for train_idx, test_idx in kf.split(iris.data, iris.target):
    # Get the training and testing data for this fold
    X_train, y_train = iris.data[train_idx], iris.target[train_idx]
    X_test, y_test = iris.data[test_idx], iris.target[test_idx]

    # Train the model on the training data for this fold
    model.fit(X_train, y_train)

    # Predict the labels for the testing data for this fold
    y_pred = model.predict(X_test)

    # Calculate the precision and recall for this fold
    precision = precision_score(y_test, y_pred, average='macro')
    recall = recall_score(y_test, y_pred, average='macro')

    # Add the precision and recall scores to the lists for all folds
    precision_scores.append(precision)
    recall_scores.append(recall)

# Print the average precision and recall scores across all folds
print("Average precision score: %0.2f" % (sum(precision_scores) / len(precision_scores)))
print("Average recall score: %0.2f" % (sum(recall_scores) / len(recall_scores)))

Average precision score: 0.95
Average recall score: 0.95